### ISSUE TITLE
Request : howto installation without docker

### ISSUE THREAD

**Issue by erdoukki** [daxAKAhackerman/suricata-lightweight-gui#3]
Hown can I start it (and install it all) without docker...
I am testing in a lxc container, and docker is not working from now, inside my debian, inside LXC !

**Comment by daxAKAhackerman** [comment]
Running Docker in LXC can be pretty tricky indeed, but not impossible, as explained [here](https://discuss.linuxcontainers.org/t/working-install-of-docker-ce-in-lxc-unprivileged-container-in-proxmox/3828). 

This project was not really intended to run without docker, but technically you could use the contents of [Dockerfile.frontend](https://github.com/daxAKAhackerman/suricata-lightweight-gui/blob/master/Dockerfile.frontend), [Dockerfile.backend](https://github.com/daxAKAhackerman/suricata-lightweight-gui/blob/master/Dockerfile.backend) and [docker-compose.yml](https://github.com/daxAKAhackerman/suricata-lightweight-gui/blob/master/docker-compose.yml) as a sort of step-by-step guide to deploy it without docker. However, knowledge of Docker and docker-compose is required to do so.

**Comment by erdoukki** [comment]
Okay, thanks for the advice... It is mainly working (will write a tutorial if requested)...
What is the "EVE" block meaning ?
```
    volumes: 
      - '/var/log/suricata/eve.json:/var/log/suricata/eve.json'
    environment:
      SURICATA_EVE_FILE: '/var/log/suricata/eve.json'
```

I get error from API :
```
ERROR:app:Exception on /api/eve [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/server/app/api/eve.py", line 24, in get_eve
    with FileReadBackwards(Config.SURICATA_EVE_FILE, encoding="utf-8") as file:
  File "/usr/local/lib/python3.7/dist-packages/file_read_backwards/file_read_backwards.py", line 41, in __init__
    self.iterator = FileReadBackwardsIterator(io.open(self.path, mode="rb"), self.encoding, self.chunk_size)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/server/eve.json'

```

**Comment by erdoukki** [comment]
resolved with 
`admin@mySNORT:~$ sudo ln -s /var/log/suricata/eve.json /var/www/html/server/eve.json`

**Comment by daxAKAhackerman** [comment]
Glad you could get it to work! I haven't worked on that project for a little while, so let me know if there are any bugs!
